query GetAllFeatures {
  features {
    id
    name
    description
    category {
      id
      name
      backgroundColor
      description
      icon
    }
    website {
      name
      url
      logo
    }
  }
}
